apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: create-environment
  namespace: test
spec:
  steps:
    - computeResources: {}
      image: 'quay.io/ansible/ansible-runner:latest'
      name: create-env
      script: |
        set -e
        echo "Disabling SSL verification..."
        export GIT_SSL_NO_VERIFY=true
        echo "Checking if /mnt/open5gs exists..."
          if [ -d "/mnt/open5gs" ]; then
            echo "/mnt/open5gs exists. Deleting..."
            rm -rf "/mnt/open5gs"
            echo "/mnt/open5gs deleted."
          fi
        echo "Cloning Open5gs repository..."
        git clone <git-containing-open5gs-helm-chart> /mnt/open5gs

  workspaces:
    - mountPath: /mnt
      name: output
