apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: deploy-new-version
  namespace: demo
spec:
  params:
    - description: Tag of the pushed image
      name: imageTag
      type: string
  steps:
    - computeResources: {}
      image: 'alpine/helm:latest'
      name: print-image-info
      script: |
        #!/bin/sh
        set -e
        echo "$(params.image_registry)"
        echo "Tag is"
        echo "$(params.imageTag)"
        echo "Checking pods"
        echo "Listing all namespaces in the cluster:"
        helm list --all-namespaces
  workspaces:
    - mountPath: /mnt
      name: output

