apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: destroy
  namespace: test
spec:
  steps:
    - computeResources: {}
      image: quay.io/centos/centos
      name: no-op
      script: |
        #!/bin/sh
        rm -r /mnt/ansible-repo
        rm -rf /mnt/output
        rm -rf /mnt/open5gs
        echo "Destroyed"
  workspaces:
    - mountPath: /mnt
      name: output
