apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: promote-new-version
  namespace: demo
spec:
  params:
    - description: Registry of the pushed image
      name: image_registry
      type: string
    - description: Tag of the pushed image
      name: imageTag
      type: string
  steps:
    - computeResources: {}
      image: quay.io/containers/skopeo
      name: pull-source-image
      script: |
        #!/bin/bash

        # Source and destination registry details
        SOURCE_REGISTRY="lab-registry.tmetse.bos2.lab"
        DEST_REGISTRY="lab-registry.tmetse.bos2.lab"
        SOURCE_REPO="saahmed/inbound-registry"
        DEST_REPO="saahmed/integration-registry"
        echo "$(params.imageTag)"
        TAG="$(params.imageTag)"
        # Copy the image
        echo "Copying image from $SOURCE_REGISTRY/$SOURCE_REPO to $DEST_REGISTRY/$DEST_REPO..."
        skopeo copy --src-tls-verify=false --dest-tls-verify=false \
        --dest-creds=$(cat /secret/username):$(cat /secret/password) \
        "docker://$SOURCE_REGISTRY/$SOURCE_REPO:$TAG" "docker://$DEST_REGISTRY/$DEST_REPO:$TAG"
        echo "Image copy completed!"
      volumeMounts:
        - mountPath: /secret
          name: quay-auth
          readOnly: true
  volumes:
    - name: quay-auth
      secret:
        secretName: quay-auth-secret
  workspaces:
    - mountPath: /mnt
      name: output
