apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: results-validation
  namespace: test
spec:
  steps:
    - computeResources: {}
      image: 'quay.io/ansible/ansible-runner:latest'
      name: clone-repository
      script: |
        #!/bin/sh
        cd /mnt/ansible-repo
        mkdir -p /mnt/output
        echo "Running Ansible Playbook..."
        ansible-playbook /mnt/ansible-repo/results_validation.yml
  workspaces:
    - mountPath: /mnt
      name: output
