apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: test-execution-task
  namespace: test
spec:
  steps:
    - computeResources: {}
      image: 'quay.io/ansible/ansible-runner:latest'
      name: clone-repository
      script: |
        #!/bin/sh
        set -e
        ls -l /mnt

        echo "Update Config Response is:"
        update_config_response=$(cat /mnt/output/update_config.txt)
        echo "update_config_response"



        cd /mnt/ansible-repo
        pwd  # Prints the current directory
        ls -al  # Lists the contents of the directory
        mkdir -p /mnt/output
        echo "Running Ansible Playbook..."
        ansible-playbook /mnt/ansible-repo/test_execution.yml
  workspaces:
    - mountPath: /mnt
      name: output
