apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: pcf-event-listener
  namespace: demo
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: TriggerBinding
          ref: pcf-trigger-binding
      name: GitHub-listener
      template:
        ref: pcf-trigger-template
